[package]
name = "ha-cec-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
faux = "0.1.10"
rumqttc = "0.24.0"
serde_json = "1.0.125"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"
toml = "0.8.19"

[dependencies.serde]
version="1.0.208"
features = ["derive"]
